// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParklaysBackend.Data;

#nullable disable

namespace ParklaysBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201070206_FixParkingSessionFK")]
    partial class FixParkingSessionFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParklaysBackend.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LotId")
                        .HasColumnType("integer")
                        .HasColumnName("lotid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LotId");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("ParklaysBackend.Models.MasterAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MasterAdmins");
                });

            modelBuilder.Entity("ParklaysBackend.Models.ParkingLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("parkinglots", (string)null);
                });

            modelBuilder.Entity("ParklaysBackend.Models.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_time");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_time");

                    b.Property<int>("LotId")
                        .HasColumnType("integer")
                        .HasColumnName("lotid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("ScannedBy")
                        .HasColumnType("integer")
                        .HasColumnName("scanned_by");

                    b.Property<long>("SlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("slotid");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer")
                        .HasColumnName("slotnumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_color");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_number");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("SlotId");

                    b.ToTable("parkingsessions", (string)null);
                });

            modelBuilder.Entity("ParklaysBackend.Models.ParkingSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Fid")
                        .HasColumnType("bigint")
                        .HasColumnName("fid");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<bool>("IsBike")
                        .HasColumnType("boolean")
                        .HasColumnName("isbike");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("isfree");

                    b.Property<long>("LotId")
                        .HasColumnType("bigint")
                        .HasColumnName("lotid");

                    b.Property<long>("SlotNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("slotnumber");

                    b.HasKey("Id");

                    b.ToTable("parkingslots", (string)null);
                });

            modelBuilder.Entity("ParklaysBackend.Models.SuperAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("superadmins", (string)null);
                });

            modelBuilder.Entity("ParklaysBackend.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("VehicleColor")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_color");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_number");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.ToTable("userprofiles");
                });

            modelBuilder.Entity("ParklaysBackend.Models.Admin", b =>
                {
                    b.HasOne("ParklaysBackend.Models.SuperAdmin", "SuperAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParklaysBackend.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParkingLot");

                    b.Navigation("SuperAdmin");
                });

            modelBuilder.Entity("ParklaysBackend.Models.ParkingSession", b =>
                {
                    b.HasOne("ParklaysBackend.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParklaysBackend.Models.ParkingSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");

                    b.Navigation("Slot");
                });
#pragma warning restore 612, 618
        }
    }
}
