// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKRBuyg15_qnRrKKsJ9lu9a20zuGZHSxI',    //changed
    appId: '1:699402641937:web:68193d4efcdc4613a9c7b0',
    messagingSenderId: '699402641937',
    projectId: 'parklays-ae03d',
    authDomain: 'parklays-ae03d.firebaseapp.com',
    storageBucket: 'parklays-ae03d.firebasestorage.app',
    measurementId: 'G-MRH0EVJE7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEvQytIBIrGJeSB5xauBDMYxI1QGDuHQ',    //changed
    appId: '1:699402641937:android:b151a5e230e3bab7a9c7b0',
    messagingSenderId: '699402641937',
    projectId: 'parklays-ae03d',
    storageBucket: 'parklays-ae03d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhcgxitq59W01OVKK3SVslmp1Lg3ns_Kc',
    appId: '1:699402641937:ios:952bb702ea67d3c6a9c7b0',
    messagingSenderId: '699402641937',
    projectId: 'parklays-ae03d',
    storageBucket: 'parklays-ae03d.firebasestorage.app',
    iosBundleId: 'com.example.parklays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhcgxitq59W01OVKK3SVslmp1Lg3ns_Kc',
    appId: '1:699402641937:ios:952bb702ea67d3c6a9c7b0',
    messagingSenderId: '699402641937',
    projectId: 'parklays-ae03d',
    storageBucket: 'parklays-ae03d.firebasestorage.app',
    iosBundleId: 'com.example.parklays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKRBuyg15_qnRrKKsJ9lu9a20zuGZHSxI',      //changed
    appId: '1:699402641937:web:6f8bf1199c91c2eca9c7b0',
    messagingSenderId: '699402641937',
    projectId: 'parklays-ae03d',
    authDomain: 'parklays-ae03d.firebaseapp.com',
    storageBucket: 'parklays-ae03d.firebasestorage.app',
    measurementId: 'G-PCYC96YX3G',
  );
}
